---
- name: Add Podman apt repository key
  apt_key:
    url: "{{ opensuse_repo_url }}{{ ansible_distribution_version }}/Release.key"
    state: present

- name: Setup Podman apt repository
  apt_repository:
    repo: "deb {{ opensuse_repo_url }}{{ ansible_distribution_version }}/ /"
    state: present
        
- name: Install admin tools
  become: yes
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop:
    - git 
    - python3.8
    - podman
    
- name: Ensure {{ rundeck_user }} user
  user:
    name: "{{ rundeck_user }}"
    comment: Rundeck Service Account
    shell: /bin/bash
    groups: adm, sudo
    create_home: yes
    home: "{{ rundeck_home }}"
    system: yes
    state: present

- name: Ensure {{ rundeck_home }}/server directory
  file:
    name: "{{ rundeck_home }}/server"
    owner: rundeck
    group: rundeck
    state: directory

- name: Ensure {{ rundeck_home }}/server/data directory
  file:
    name: "{{ rundeck_home }}/server/data"
    owner: rundeck
    group: rundeck
    state: directory
# TODO: fix this
    mode: 0777 

- name: Setup Rundeck container
  vars:
    container_run_as_user: "{{ rundeck_user }}"
    container_run_as_group: "{{ rundeck_user }}"
    container_image_list: 
      - "rundeck/rundeck:{{ rundeck_image_version }}"
    container_name: rundeck
    container_run_args: >-
      --rm
      --label "io.containers.autoupdate=image"
      -e RUNDECK_GRAILS_URL="http://{{ inventory_hostname }}.{{ top_level_domain }}:4440"
      -v /home/rundeck/server/data:/home/rundeck/server/data:Z
      -p 4440:4440
    systemd_TimeoutStartSec: 180
    container_state: running
    #container_firewall_ports:
    #  - 8080/tcp
    #  - 8443/tcp  
  import_role:
    name: ikke_t.podman_container_systemd
  tags: rundeck

